import { AlignmentResult, ParsedDiff, AnalysisFile } from './types';

// ─── Analysis Report Generator ────────────────────────────────────────────────

export function generateAnalysisReport(
  alignment: AlignmentResult,
  diff: ParsedDiff,
  prNumber?: number,
  commitSha?: string
): AnalysisFile {
  const identifier = prNumber ? `PR #${prNumber}` : `Commit ${commitSha?.slice(0, 7) ?? 'unknown'}`;
  const fileName = prNumber
    ? `pr-${prNumber}-analysis.md`
    : `commit-${commitSha?.slice(0, 7) ?? 'unknown'}-analysis.md`;

  const filePath = `feature-alignment/${fileName}`;

  const checkTimestamp = new Date().toISOString().replace('T', ' ').replace(/\.\d+Z$/, ' UTC');

  const statusEmoji = alignment.verdict === 'misaligned' ? '❌ MISALIGNED'
    : alignment.verdict === 'partial' ? '⚠️ PARTIALLY ALIGNED'
    : '❓ SPEC NOT FOUND';

  const content = buildAnalysisContent({
    identifier,
    alignment,
    diff,
    checkTimestamp,
    statusEmoji,
  });

  return {
    path: filePath,
    content,
    prNumber,
    commitSha,
  };
}

interface BuildOptions {
  identifier: string;
  alignment: AlignmentResult;
  diff: ParsedDiff;
  checkTimestamp: string;
  statusEmoji: string;
}

function buildAnalysisContent(opts: BuildOptions): string {
  const { identifier, alignment, diff, checkTimestamp, statusEmoji } = opts;

  const lines: string[] = [
    `# SpecSync Alignment Report`,
    `**${identifier}**`,
    alignment.specPage ? `**Spec:** ${alignment.specPage}${alignment.specVersion ? ` v${alignment.specVersion}` : ''}` : '',
    `**Checked:** ${checkTimestamp}`,
    `**Confidence:** ${alignment.confidence}%`,
    `**Status:** ${statusEmoji}`,
    '',
    '---',
    '',
  ];

  // Summary
  lines.push('## Summary', '', alignment.summary, '');

  // Changed files
  if (diff.files.length > 0) {
    lines.push('## Changed Files', '');
    for (const file of diff.files) {
      lines.push(`- \`${file.path}\` (${file.status}, +${file.additions}/-${file.deletions})`);
    }
    lines.push('');
  }

  // Gaps
  if (alignment.gaps.length > 0) {
    lines.push('## Gaps Found', '');

    const blocking = alignment.gaps.filter(g => g.severity === 'blocking');
    const warnings = alignment.gaps.filter(g => g.severity === 'warning');

    if (blocking.length > 0) {
      lines.push('### ❌ Blocking Issues', '');
      for (const gap of blocking) {
        lines.push(`- [ ] ${gap.description}`);
        if (gap.relatedFile) lines.push(`  > File: \`${gap.relatedFile}\``);
        if (gap.relatedFunction) lines.push(`  > Function: \`${gap.relatedFunction}()\``);
        if (gap.criteriaId) lines.push(`  > Acceptance Criteria: #${gap.criteriaId}`);
      }
      lines.push('');
    }

    if (warnings.length > 0) {
      lines.push('### ⚠️ Warnings', '');
      for (const gap of warnings) {
        lines.push(`- [ ] ${gap.description}`);
        if (gap.relatedFile) lines.push(`  > File: \`${gap.relatedFile}\``);
      }
      lines.push('');
    }
  }

  // Aligned criteria (if partial)
  if (alignment.alignedCriteria.length > 0) {
    lines.push('## ✅ Implemented Criteria', '');
    for (const id of alignment.alignedCriteria) {
      lines.push(`- Acceptance Criteria #${id} — implemented`);
    }
    lines.push('');
  }

  // Pending tests (blocked by gaps)
  if (alignment.pendingTests.length > 0) {
    lines.push(
      '## Tests That Cannot Be Written Until Gaps Are Fixed',
      '',
      'The following test cases are required by the spec but cannot be generated',
      'because the implementation does not exist yet:',
      '',
    );

    const byType = groupBy(alignment.pendingTests, t => t.type);
    const typeLabels: Record<string, string> = {
      'unit-positive': 'Unit — Positive',
      'unit-negative': 'Unit — Negative',
      'unit-edge': 'Unit — Edge Cases',
      'integration': 'Integration',
      'contract': 'Contract',
    };

    for (const [type, tests] of Object.entries(byType)) {
      lines.push(`### ${typeLabels[type] ?? type}`, '');
      for (const test of tests) {
        lines.push(`- \`${test.description}\``);
        if (test.blockedReason) lines.push(`  ↳ Blocked: ${test.blockedReason}`);
      }
      lines.push('');
    }
  }

  // Next steps
  lines.push(
    '---',
    '',
    '## Next Steps',
    '',
    '**If you missed requirements in the spec:**',
    'Implement the missing functionality above and push a new commit.',
    'SpecSync will automatically re-evaluate this branch.',
    '',
    '**If you believe the requirements have changed:**',
    'Do NOT open a PR yet. Contact your architect or PM and ask them to update the Wiki spec.',
    'SpecSync will automatically re-check this branch once the spec is updated.',
    '',
    '---',
    '',
    `*Generated by [SpecSync Agent](https://github.com/specsync/specsync-agent) · ${checkTimestamp}*`,
  );

  return lines.filter(l => l !== undefined).join('\n');
}

// Simple groupBy utility
function groupBy<T>(arr: T[], key: (item: T) => string): Record<string, T[]> {
  return arr.reduce((acc, item) => {
    const k = key(item);
    if (!acc[k]) acc[k] = [];
    acc[k].push(item);
    return acc;
  }, {} as Record<string, T[]>);
}
